cmd/**/*.go
internal/**/*.go
templx/**/*.go
internal/**/*.yml
misc/tailwind/templui.css
.env
Makefile
modd.conf {
  prep: "make -o generate build"
  daemon: "make CMD='bin/server' run-with-env"
}

internal/**/*.templ
templx/**/*.templ {
  prep: make build-server
}
