// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/pluginsdk/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginDescriptor_Capability int32

const (
	PluginDescriptor_CAPABILITY_UNSPECIFIED PluginDescriptor_Capability = 0
	PluginDescriptor_PRE_REQUEST            PluginDescriptor_Capability = 1
	PluginDescriptor_POST_RESPONSE          PluginDescriptor_Capability = 2
	PluginDescriptor_RESOLVE_MODEL          PluginDescriptor_Capability = 3
	PluginDescriptor_LIST_MODELS            PluginDescriptor_Capability = 4
)

// Enum value maps for PluginDescriptor_Capability.
var (
	PluginDescriptor_Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "PRE_REQUEST",
		2: "POST_RESPONSE",
		3: "RESOLVE_MODEL",
		4: "LIST_MODELS",
	}
	PluginDescriptor_Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED": 0,
		"PRE_REQUEST":            1,
		"POST_RESPONSE":          2,
		"RESOLVE_MODEL":          3,
		"LIST_MODELS":            4,
	}
)

func (x PluginDescriptor_Capability) Enum() *PluginDescriptor_Capability {
	p := new(PluginDescriptor_Capability)
	*p = x
	return p
}

func (x PluginDescriptor_Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginDescriptor_Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pluginsdk_proto_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginDescriptor_Capability) Type() protoreflect.EnumType {
	return &file_pkg_pluginsdk_proto_plugin_proto_enumTypes[0]
}

func (x PluginDescriptor_Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginDescriptor_Capability.Descriptor instead.
func (PluginDescriptor_Capability) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{7, 0}
}

type InitializeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HostServiceBrokerId uint32                 `protobuf:"varint,1,opt,name=host_service_broker_id,json=hostServiceBrokerId,proto3" json:"host_service_broker_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetHostServiceBrokerId() uint32 {
	if x != nil {
		return x.HostServiceBrokerId
	}
	return 0
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpUiPort    uint32                 `protobuf:"varint,1,opt,name=http_ui_port,json=httpUiPort,proto3" json:"http_ui_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResponse) GetHttpUiPort() uint32 {
	if x != nil {
		return x.HttpUiPort
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetConfigRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigResponse) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type SaveConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigRequest) Reset() {
	*x = SaveConfigRequest{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigRequest) ProtoMessage() {}

func (x *SaveConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigRequest.ProtoReflect.Descriptor instead.
func (*SaveConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SaveConfigRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SaveConfigRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *SaveConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type SaveConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigResponse) Reset() {
	*x = SaveConfigResponse{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigResponse) ProtoMessage() {}

func (x *SaveConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{5}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{6}
}

type PluginDescriptor struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Name             string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                        `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description      string                        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities     []PluginDescriptor_Capability `protobuf:"varint,4,rep,packed,name=capabilities,proto3,enum=xolo.plugin.v1.PluginDescriptor_Capability" json:"capabilities,omitempty"`
	ConfigSchema     string                        `protobuf:"bytes,5,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	UserConfigSchema string                        `protobuf:"bytes,6,opt,name=user_config_schema,json=userConfigSchema,proto3" json:"user_config_schema,omitempty"`
	DefaultRequired  bool                          `protobuf:"varint,7,opt,name=default_required,json=defaultRequired,proto3" json:"default_required,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginDescriptor) Reset() {
	*x = PluginDescriptor{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDescriptor) ProtoMessage() {}

func (x *PluginDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDescriptor.ProtoReflect.Descriptor instead.
func (*PluginDescriptor) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginDescriptor) GetCapabilities() []PluginDescriptor_Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginDescriptor) GetConfigSchema() string {
	if x != nil {
		return x.ConfigSchema
	}
	return ""
}

func (x *PluginDescriptor) GetUserConfigSchema() string {
	if x != nil {
		return x.UserConfigSchema
	}
	return ""
}

func (x *PluginDescriptor) GetDefaultRequired() bool {
	if x != nil {
		return x.DefaultRequired
	}
	return false
}

type RequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId        string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ConfigJson     string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	UserConfigJson string                 `protobuf:"bytes,5,opt,name=user_config_json,json=userConfigJson,proto3" json:"user_config_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *RequestContext) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RequestContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestContext) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RequestContext) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *RequestContext) GetUserConfigJson() string {
	if x != nil {
		return x.UserConfigJson
	}
	return ""
}

type ModelInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ProxyName                  string                 `protobuf:"bytes,1,opt,name=proxy_name,json=proxyName,proto3" json:"proxy_name,omitempty"`
	RealModel                  string                 `protobuf:"bytes,2,opt,name=real_model,json=realModel,proto3" json:"real_model,omitempty"`
	ProviderId                 string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	PromptCostPer_1KTokens     float64                `protobuf:"fixed64,4,opt,name=prompt_cost_per_1k_tokens,json=promptCostPer1kTokens,proto3" json:"prompt_cost_per_1k_tokens,omitempty"`
	CompletionCostPer_1KTokens float64                `protobuf:"fixed64,5,opt,name=completion_cost_per_1k_tokens,json=completionCostPer1kTokens,proto3" json:"completion_cost_per_1k_tokens,omitempty"`
	TokenLimit                 int64                  `protobuf:"varint,6,opt,name=token_limit,json=tokenLimit,proto3" json:"token_limit,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ModelInfo) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *ModelInfo) GetRealModel() string {
	if x != nil {
		return x.RealModel
	}
	return ""
}

func (x *ModelInfo) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ModelInfo) GetPromptCostPer_1KTokens() float64 {
	if x != nil {
		return x.PromptCostPer_1KTokens
	}
	return 0
}

func (x *ModelInfo) GetCompletionCostPer_1KTokens() float64 {
	if x != nil {
		return x.CompletionCostPer_1KTokens
	}
	return 0
}

func (x *ModelInfo) GetTokenLimit() int64 {
	if x != nil {
		return x.TokenLimit
	}
	return 0
}

type PreRequestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *RequestContext        `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	MessagesJson  string                 `protobuf:"bytes,3,opt,name=messages_json,json=messagesJson,proto3" json:"messages_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreRequestInput) Reset() {
	*x = PreRequestInput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRequestInput) ProtoMessage() {}

func (x *PreRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRequestInput.ProtoReflect.Descriptor instead.
func (*PreRequestInput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PreRequestInput) GetCtx() *RequestContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *PreRequestInput) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PreRequestInput) GetMessagesJson() string {
	if x != nil {
		return x.MessagesJson
	}
	return ""
}

type PreRequestOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreRequestOutput) Reset() {
	*x = PreRequestOutput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreRequestOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRequestOutput) ProtoMessage() {}

func (x *PreRequestOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRequestOutput.ProtoReflect.Descriptor instead.
func (*PreRequestOutput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PreRequestOutput) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PreRequestOutput) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type PostResponseInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ctx              *RequestContext        `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Model            string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,4,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	HadError         bool                   `protobuf:"varint,5,opt,name=had_error,json=hadError,proto3" json:"had_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostResponseInput) Reset() {
	*x = PostResponseInput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponseInput) ProtoMessage() {}

func (x *PostResponseInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponseInput.ProtoReflect.Descriptor instead.
func (*PostResponseInput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PostResponseInput) GetCtx() *RequestContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *PostResponseInput) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PostResponseInput) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *PostResponseInput) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *PostResponseInput) GetHadError() bool {
	if x != nil {
		return x.HadError
	}
	return false
}

type PostResponseOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponseOutput) Reset() {
	*x = PostResponseOutput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponseOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponseOutput) ProtoMessage() {}

func (x *PostResponseOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponseOutput.ProtoReflect.Descriptor instead.
func (*PostResponseOutput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{13}
}

type ResolveModelInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ctx             *RequestContext        `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	RequestedModel  string                 `protobuf:"bytes,2,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	AvailableModels []*ModelInfo           `protobuf:"bytes,3,rep,name=available_models,json=availableModels,proto3" json:"available_models,omitempty"`
	MessagesJson    string                 `protobuf:"bytes,4,opt,name=messages_json,json=messagesJson,proto3" json:"messages_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveModelInput) Reset() {
	*x = ResolveModelInput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveModelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveModelInput) ProtoMessage() {}

func (x *ResolveModelInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveModelInput.ProtoReflect.Descriptor instead.
func (*ResolveModelInput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveModelInput) GetCtx() *RequestContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ResolveModelInput) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

func (x *ResolveModelInput) GetAvailableModels() []*ModelInfo {
	if x != nil {
		return x.AvailableModels
	}
	return nil
}

func (x *ResolveModelInput) GetMessagesJson() string {
	if x != nil {
		return x.MessagesJson
	}
	return ""
}

type ResolveModelOutput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResolvedProxyName string                 `protobuf:"bytes,1,opt,name=resolved_proxy_name,json=resolvedProxyName,proto3" json:"resolved_proxy_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveModelOutput) Reset() {
	*x = ResolveModelOutput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveModelOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveModelOutput) ProtoMessage() {}

func (x *ResolveModelOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveModelOutput.ProtoReflect.Descriptor instead.
func (*ResolveModelOutput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveModelOutput) GetResolvedProxyName() string {
	if x != nil {
		return x.ResolvedProxyName
	}
	return ""
}

type ListModelsInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ctx             *RequestContext        `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	AvailableModels []*ModelInfo           `protobuf:"bytes,2,rep,name=available_models,json=availableModels,proto3" json:"available_models,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListModelsInput) Reset() {
	*x = ListModelsInput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsInput) ProtoMessage() {}

func (x *ListModelsInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsInput.ProtoReflect.Descriptor instead.
func (*ListModelsInput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ListModelsInput) GetCtx() *RequestContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *ListModelsInput) GetAvailableModels() []*ModelInfo {
	if x != nil {
		return x.AvailableModels
	}
	return nil
}

type ListModelsOutput struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AdditionalProxyNames []string               `protobuf:"bytes,1,rep,name=additional_proxy_names,json=additionalProxyNames,proto3" json:"additional_proxy_names,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListModelsOutput) Reset() {
	*x = ListModelsOutput{}
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsOutput) ProtoMessage() {}

func (x *ListModelsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginsdk_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsOutput.ProtoReflect.Descriptor instead.
func (*ListModelsOutput) Descriptor() ([]byte, []int) {
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ListModelsOutput) GetAdditionalProxyNames() []string {
	if x != nil {
		return x.AdditionalProxyNames
	}
	return nil
}

var File_pkg_pluginsdk_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_pluginsdk_proto_plugin_proto_rawDesc = "" +
	"\n" +
	" pkg/pluginsdk/proto/plugin.proto\x12\x0exolo.plugin.v1\"H\n" +
	"\x11InitializeRequest\x123\n" +
	"\x16host_service_broker_id\x18\x01 \x01(\rR\x13hostServiceBrokerId\"6\n" +
	"\x12InitializeResponse\x12 \n" +
	"\fhttp_ui_port\x18\x01 \x01(\rR\n" +
	"httpUiPort\"J\n" +
	"\x10GetConfigRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"4\n" +
	"\x11GetConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"l\n" +
	"\x11SaveConfigRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"\x14\n" +
	"\x12SaveConfigResponse\"\x11\n" +
	"\x0fDescribeRequest\"\xa3\x03\n" +
	"\x10PluginDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12O\n" +
	"\fcapabilities\x18\x04 \x03(\x0e2+.xolo.plugin.v1.PluginDescriptor.CapabilityR\fcapabilities\x12#\n" +
	"\rconfig_schema\x18\x05 \x01(\tR\fconfigSchema\x12,\n" +
	"\x12user_config_schema\x18\x06 \x01(\tR\x10userConfigSchema\x12)\n" +
	"\x10default_required\x18\a \x01(\bR\x0fdefaultRequired\"p\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPRE_REQUEST\x10\x01\x12\x11\n" +
	"\rPOST_RESPONSE\x10\x02\x12\x11\n" +
	"\rRESOLVE_MODEL\x10\x03\x12\x0f\n" +
	"\vLIST_MODELS\x10\x04\"\xa6\x01\n" +
	"\x0eRequestContext\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\x12(\n" +
	"\x10user_config_json\x18\x05 \x01(\tR\x0euserConfigJson\"\x87\x02\n" +
	"\tModelInfo\x12\x1d\n" +
	"\n" +
	"proxy_name\x18\x01 \x01(\tR\tproxyName\x12\x1d\n" +
	"\n" +
	"real_model\x18\x02 \x01(\tR\trealModel\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x128\n" +
	"\x19prompt_cost_per_1k_tokens\x18\x04 \x01(\x01R\x15promptCostPer1kTokens\x12@\n" +
	"\x1dcompletion_cost_per_1k_tokens\x18\x05 \x01(\x01R\x19completionCostPer1kTokens\x12\x1f\n" +
	"\vtoken_limit\x18\x06 \x01(\x03R\n" +
	"tokenLimit\"~\n" +
	"\x0fPreRequestInput\x120\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1e.xolo.plugin.v1.RequestContextR\x03ctx\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rmessages_json\x18\x03 \x01(\tR\fmessagesJson\"W\n" +
	"\x10PreRequestOutput\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\"\xca\x01\n" +
	"\x11PostResponseInput\x120\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1e.xolo.plugin.v1.RequestContextR\x03ctx\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x04 \x01(\x03R\x10completionTokens\x12\x1b\n" +
	"\thad_error\x18\x05 \x01(\bR\bhadError\"\x14\n" +
	"\x12PostResponseOutput\"\xd9\x01\n" +
	"\x11ResolveModelInput\x120\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1e.xolo.plugin.v1.RequestContextR\x03ctx\x12'\n" +
	"\x0frequested_model\x18\x02 \x01(\tR\x0erequestedModel\x12D\n" +
	"\x10available_models\x18\x03 \x03(\v2\x19.xolo.plugin.v1.ModelInfoR\x0favailableModels\x12#\n" +
	"\rmessages_json\x18\x04 \x01(\tR\fmessagesJson\"D\n" +
	"\x12ResolveModelOutput\x12.\n" +
	"\x13resolved_proxy_name\x18\x01 \x01(\tR\x11resolvedProxyName\"\x89\x01\n" +
	"\x0fListModelsInput\x120\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1e.xolo.plugin.v1.RequestContextR\x03ctx\x12D\n" +
	"\x10available_models\x18\x02 \x03(\v2\x19.xolo.plugin.v1.ModelInfoR\x0favailableModels\"H\n" +
	"\x10ListModelsOutput\x124\n" +
	"\x16additional_proxy_names\x18\x01 \x03(\tR\x14additionalProxyNames2\x80\x04\n" +
	"\n" +
	"XoloPlugin\x12M\n" +
	"\bDescribe\x12\x1f.xolo.plugin.v1.DescribeRequest\x1a .xolo.plugin.v1.PluginDescriptor\x12S\n" +
	"\n" +
	"Initialize\x12!.xolo.plugin.v1.InitializeRequest\x1a\".xolo.plugin.v1.InitializeResponse\x12O\n" +
	"\n" +
	"PreRequest\x12\x1f.xolo.plugin.v1.PreRequestInput\x1a .xolo.plugin.v1.PreRequestOutput\x12U\n" +
	"\fPostResponse\x12!.xolo.plugin.v1.PostResponseInput\x1a\".xolo.plugin.v1.PostResponseOutput\x12U\n" +
	"\fResolveModel\x12!.xolo.plugin.v1.ResolveModelInput\x1a\".xolo.plugin.v1.ResolveModelOutput\x12O\n" +
	"\n" +
	"ListModels\x12\x1f.xolo.plugin.v1.ListModelsInput\x1a .xolo.plugin.v1.ListModelsOutput2\xb8\x01\n" +
	"\x0fXoloHostService\x12P\n" +
	"\tGetConfig\x12 .xolo.plugin.v1.GetConfigRequest\x1a!.xolo.plugin.v1.GetConfigResponse\x12S\n" +
	"\n" +
	"SaveConfig\x12!.xolo.plugin.v1.SaveConfigRequest\x1a\".xolo.plugin.v1.SaveConfigResponseB.Z,github.com/bornholm/xolo/pkg/pluginsdk/protob\x06proto3"

var (
	file_pkg_pluginsdk_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_pluginsdk_proto_plugin_proto_rawDescData []byte
)

func file_pkg_pluginsdk_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_pluginsdk_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_pluginsdk_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pluginsdk_proto_plugin_proto_rawDesc), len(file_pkg_pluginsdk_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_pluginsdk_proto_plugin_proto_rawDescData
}

var file_pkg_pluginsdk_proto_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pluginsdk_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_pluginsdk_proto_plugin_proto_goTypes = []any{
	(PluginDescriptor_Capability)(0), // 0: xolo.plugin.v1.PluginDescriptor.Capability
	(*InitializeRequest)(nil),        // 1: xolo.plugin.v1.InitializeRequest
	(*InitializeResponse)(nil),       // 2: xolo.plugin.v1.InitializeResponse
	(*GetConfigRequest)(nil),         // 3: xolo.plugin.v1.GetConfigRequest
	(*GetConfigResponse)(nil),        // 4: xolo.plugin.v1.GetConfigResponse
	(*SaveConfigRequest)(nil),        // 5: xolo.plugin.v1.SaveConfigRequest
	(*SaveConfigResponse)(nil),       // 6: xolo.plugin.v1.SaveConfigResponse
	(*DescribeRequest)(nil),          // 7: xolo.plugin.v1.DescribeRequest
	(*PluginDescriptor)(nil),         // 8: xolo.plugin.v1.PluginDescriptor
	(*RequestContext)(nil),           // 9: xolo.plugin.v1.RequestContext
	(*ModelInfo)(nil),                // 10: xolo.plugin.v1.ModelInfo
	(*PreRequestInput)(nil),          // 11: xolo.plugin.v1.PreRequestInput
	(*PreRequestOutput)(nil),         // 12: xolo.plugin.v1.PreRequestOutput
	(*PostResponseInput)(nil),        // 13: xolo.plugin.v1.PostResponseInput
	(*PostResponseOutput)(nil),       // 14: xolo.plugin.v1.PostResponseOutput
	(*ResolveModelInput)(nil),        // 15: xolo.plugin.v1.ResolveModelInput
	(*ResolveModelOutput)(nil),       // 16: xolo.plugin.v1.ResolveModelOutput
	(*ListModelsInput)(nil),          // 17: xolo.plugin.v1.ListModelsInput
	(*ListModelsOutput)(nil),         // 18: xolo.plugin.v1.ListModelsOutput
}
var file_pkg_pluginsdk_proto_plugin_proto_depIdxs = []int32{
	0,  // 0: xolo.plugin.v1.PluginDescriptor.capabilities:type_name -> xolo.plugin.v1.PluginDescriptor.Capability
	9,  // 1: xolo.plugin.v1.PreRequestInput.ctx:type_name -> xolo.plugin.v1.RequestContext
	9,  // 2: xolo.plugin.v1.PostResponseInput.ctx:type_name -> xolo.plugin.v1.RequestContext
	9,  // 3: xolo.plugin.v1.ResolveModelInput.ctx:type_name -> xolo.plugin.v1.RequestContext
	10, // 4: xolo.plugin.v1.ResolveModelInput.available_models:type_name -> xolo.plugin.v1.ModelInfo
	9,  // 5: xolo.plugin.v1.ListModelsInput.ctx:type_name -> xolo.plugin.v1.RequestContext
	10, // 6: xolo.plugin.v1.ListModelsInput.available_models:type_name -> xolo.plugin.v1.ModelInfo
	7,  // 7: xolo.plugin.v1.XoloPlugin.Describe:input_type -> xolo.plugin.v1.DescribeRequest
	1,  // 8: xolo.plugin.v1.XoloPlugin.Initialize:input_type -> xolo.plugin.v1.InitializeRequest
	11, // 9: xolo.plugin.v1.XoloPlugin.PreRequest:input_type -> xolo.plugin.v1.PreRequestInput
	13, // 10: xolo.plugin.v1.XoloPlugin.PostResponse:input_type -> xolo.plugin.v1.PostResponseInput
	15, // 11: xolo.plugin.v1.XoloPlugin.ResolveModel:input_type -> xolo.plugin.v1.ResolveModelInput
	17, // 12: xolo.plugin.v1.XoloPlugin.ListModels:input_type -> xolo.plugin.v1.ListModelsInput
	3,  // 13: xolo.plugin.v1.XoloHostService.GetConfig:input_type -> xolo.plugin.v1.GetConfigRequest
	5,  // 14: xolo.plugin.v1.XoloHostService.SaveConfig:input_type -> xolo.plugin.v1.SaveConfigRequest
	8,  // 15: xolo.plugin.v1.XoloPlugin.Describe:output_type -> xolo.plugin.v1.PluginDescriptor
	2,  // 16: xolo.plugin.v1.XoloPlugin.Initialize:output_type -> xolo.plugin.v1.InitializeResponse
	12, // 17: xolo.plugin.v1.XoloPlugin.PreRequest:output_type -> xolo.plugin.v1.PreRequestOutput
	14, // 18: xolo.plugin.v1.XoloPlugin.PostResponse:output_type -> xolo.plugin.v1.PostResponseOutput
	16, // 19: xolo.plugin.v1.XoloPlugin.ResolveModel:output_type -> xolo.plugin.v1.ResolveModelOutput
	18, // 20: xolo.plugin.v1.XoloPlugin.ListModels:output_type -> xolo.plugin.v1.ListModelsOutput
	4,  // 21: xolo.plugin.v1.XoloHostService.GetConfig:output_type -> xolo.plugin.v1.GetConfigResponse
	6,  // 22: xolo.plugin.v1.XoloHostService.SaveConfig:output_type -> xolo.plugin.v1.SaveConfigResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_pluginsdk_proto_plugin_proto_init() }
func file_pkg_pluginsdk_proto_plugin_proto_init() {
	if File_pkg_pluginsdk_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pluginsdk_proto_plugin_proto_rawDesc), len(file_pkg_pluginsdk_proto_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_pluginsdk_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_pluginsdk_proto_plugin_proto_depIdxs,
		EnumInfos:         file_pkg_pluginsdk_proto_plugin_proto_enumTypes,
		MessageInfos:      file_pkg_pluginsdk_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_pluginsdk_proto_plugin_proto = out.File
	file_pkg_pluginsdk_proto_plugin_proto_goTypes = nil
	file_pkg_pluginsdk_proto_plugin_proto_depIdxs = nil
}
