// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: pkg/pluginsdk/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XoloPlugin_Describe_FullMethodName     = "/xolo.plugin.v1.XoloPlugin/Describe"
	XoloPlugin_Initialize_FullMethodName   = "/xolo.plugin.v1.XoloPlugin/Initialize"
	XoloPlugin_PreRequest_FullMethodName   = "/xolo.plugin.v1.XoloPlugin/PreRequest"
	XoloPlugin_PostResponse_FullMethodName = "/xolo.plugin.v1.XoloPlugin/PostResponse"
	XoloPlugin_ResolveModel_FullMethodName = "/xolo.plugin.v1.XoloPlugin/ResolveModel"
	XoloPlugin_ListModels_FullMethodName   = "/xolo.plugin.v1.XoloPlugin/ListModels"
)

// XoloPluginClient is the client API for XoloPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XoloPluginClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*PluginDescriptor, error)
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	PreRequest(ctx context.Context, in *PreRequestInput, opts ...grpc.CallOption) (*PreRequestOutput, error)
	PostResponse(ctx context.Context, in *PostResponseInput, opts ...grpc.CallOption) (*PostResponseOutput, error)
	ResolveModel(ctx context.Context, in *ResolveModelInput, opts ...grpc.CallOption) (*ResolveModelOutput, error)
	ListModels(ctx context.Context, in *ListModelsInput, opts ...grpc.CallOption) (*ListModelsOutput, error)
}

type xoloPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewXoloPluginClient(cc grpc.ClientConnInterface) XoloPluginClient {
	return &xoloPluginClient{cc}
}

func (c *xoloPluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*PluginDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginDescriptor)
	err := c.cc.Invoke(ctx, XoloPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloPluginClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, XoloPlugin_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloPluginClient) PreRequest(ctx context.Context, in *PreRequestInput, opts ...grpc.CallOption) (*PreRequestOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreRequestOutput)
	err := c.cc.Invoke(ctx, XoloPlugin_PreRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloPluginClient) PostResponse(ctx context.Context, in *PostResponseInput, opts ...grpc.CallOption) (*PostResponseOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponseOutput)
	err := c.cc.Invoke(ctx, XoloPlugin_PostResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloPluginClient) ResolveModel(ctx context.Context, in *ResolveModelInput, opts ...grpc.CallOption) (*ResolveModelOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveModelOutput)
	err := c.cc.Invoke(ctx, XoloPlugin_ResolveModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloPluginClient) ListModels(ctx context.Context, in *ListModelsInput, opts ...grpc.CallOption) (*ListModelsOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsOutput)
	err := c.cc.Invoke(ctx, XoloPlugin_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XoloPluginServer is the server API for XoloPlugin service.
// All implementations must embed UnimplementedXoloPluginServer
// for forward compatibility.
type XoloPluginServer interface {
	Describe(context.Context, *DescribeRequest) (*PluginDescriptor, error)
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	PreRequest(context.Context, *PreRequestInput) (*PreRequestOutput, error)
	PostResponse(context.Context, *PostResponseInput) (*PostResponseOutput, error)
	ResolveModel(context.Context, *ResolveModelInput) (*ResolveModelOutput, error)
	ListModels(context.Context, *ListModelsInput) (*ListModelsOutput, error)
	mustEmbedUnimplementedXoloPluginServer()
}

// UnimplementedXoloPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXoloPluginServer struct{}

func (UnimplementedXoloPluginServer) Describe(context.Context, *DescribeRequest) (*PluginDescriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedXoloPluginServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedXoloPluginServer) PreRequest(context.Context, *PreRequestInput) (*PreRequestOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method PreRequest not implemented")
}
func (UnimplementedXoloPluginServer) PostResponse(context.Context, *PostResponseInput) (*PostResponseOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method PostResponse not implemented")
}
func (UnimplementedXoloPluginServer) ResolveModel(context.Context, *ResolveModelInput) (*ResolveModelOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveModel not implemented")
}
func (UnimplementedXoloPluginServer) ListModels(context.Context, *ListModelsInput) (*ListModelsOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedXoloPluginServer) mustEmbedUnimplementedXoloPluginServer() {}
func (UnimplementedXoloPluginServer) testEmbeddedByValue()                    {}

// UnsafeXoloPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XoloPluginServer will
// result in compilation errors.
type UnsafeXoloPluginServer interface {
	mustEmbedUnimplementedXoloPluginServer()
}

func RegisterXoloPluginServer(s grpc.ServiceRegistrar, srv XoloPluginServer) {
	// If the following call panics, it indicates UnimplementedXoloPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XoloPlugin_ServiceDesc, srv)
}

func _XoloPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloPluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloPlugin_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloPluginServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloPlugin_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloPluginServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloPlugin_PreRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloPluginServer).PreRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloPlugin_PreRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloPluginServer).PreRequest(ctx, req.(*PreRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloPlugin_PostResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostResponseInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloPluginServer).PostResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloPlugin_PostResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloPluginServer).PostResponse(ctx, req.(*PostResponseInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloPlugin_ResolveModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveModelInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloPluginServer).ResolveModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloPlugin_ResolveModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloPluginServer).ResolveModel(ctx, req.(*ResolveModelInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloPlugin_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloPluginServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloPlugin_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloPluginServer).ListModels(ctx, req.(*ListModelsInput))
	}
	return interceptor(ctx, in, info, handler)
}

// XoloPlugin_ServiceDesc is the grpc.ServiceDesc for XoloPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XoloPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xolo.plugin.v1.XoloPlugin",
	HandlerType: (*XoloPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _XoloPlugin_Describe_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _XoloPlugin_Initialize_Handler,
		},
		{
			MethodName: "PreRequest",
			Handler:    _XoloPlugin_PreRequest_Handler,
		},
		{
			MethodName: "PostResponse",
			Handler:    _XoloPlugin_PostResponse_Handler,
		},
		{
			MethodName: "ResolveModel",
			Handler:    _XoloPlugin_ResolveModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _XoloPlugin_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pluginsdk/proto/plugin.proto",
}

const (
	XoloHostService_GetConfig_FullMethodName  = "/xolo.plugin.v1.XoloHostService/GetConfig"
	XoloHostService_SaveConfig_FullMethodName = "/xolo.plugin.v1.XoloHostService/SaveConfig"
	XoloHostService_ListModels_FullMethodName = "/xolo.plugin.v1.XoloHostService/ListModels"
)

// XoloHostServiceClient is the client API for XoloHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XoloHostServiceClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	ListModels(ctx context.Context, in *ListModelsForOrgRequest, opts ...grpc.CallOption) (*ListModelsForOrgResponse, error)
}

type xoloHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXoloHostServiceClient(cc grpc.ClientConnInterface) XoloHostServiceClient {
	return &xoloHostServiceClient{cc}
}

func (c *xoloHostServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, XoloHostService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloHostServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, XoloHostService_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xoloHostServiceClient) ListModels(ctx context.Context, in *ListModelsForOrgRequest, opts ...grpc.CallOption) (*ListModelsForOrgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsForOrgResponse)
	err := c.cc.Invoke(ctx, XoloHostService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XoloHostServiceServer is the server API for XoloHostService service.
// All implementations must embed UnimplementedXoloHostServiceServer
// for forward compatibility.
type XoloHostServiceServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	ListModels(context.Context, *ListModelsForOrgRequest) (*ListModelsForOrgResponse, error)
	mustEmbedUnimplementedXoloHostServiceServer()
}

// UnimplementedXoloHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXoloHostServiceServer struct{}

func (UnimplementedXoloHostServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedXoloHostServiceServer) SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedXoloHostServiceServer) ListModels(context.Context, *ListModelsForOrgRequest) (*ListModelsForOrgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedXoloHostServiceServer) mustEmbedUnimplementedXoloHostServiceServer() {}
func (UnimplementedXoloHostServiceServer) testEmbeddedByValue()                         {}

// UnsafeXoloHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XoloHostServiceServer will
// result in compilation errors.
type UnsafeXoloHostServiceServer interface {
	mustEmbedUnimplementedXoloHostServiceServer()
}

func RegisterXoloHostServiceServer(s grpc.ServiceRegistrar, srv XoloHostServiceServer) {
	// If the following call panics, it indicates UnimplementedXoloHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XoloHostService_ServiceDesc, srv)
}

func _XoloHostService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloHostServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloHostService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloHostServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloHostService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloHostServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloHostService_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloHostServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XoloHostService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsForOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoloHostServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XoloHostService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoloHostServiceServer).ListModels(ctx, req.(*ListModelsForOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XoloHostService_ServiceDesc is the grpc.ServiceDesc for XoloHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XoloHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xolo.plugin.v1.XoloHostService",
	HandlerType: (*XoloHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _XoloHostService_GetConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _XoloHostService_SaveConfig_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _XoloHostService_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pluginsdk/proto/plugin.proto",
}
